#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect above requirements
sudo apt-get update
sudo apt-get -y install nginx
sudo echo -e 'Holberton School' > /var/www/html/index.html
sudo /etc/init.d/nginx start
