#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect above requirements
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
service nginx start
