#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect above requirements
apt-get update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me$ https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default
service nginx start
