#!/usr/bin/env bash
# The redirection must be a "301 Moved Permanently"
sudo apt-get update
sudo apt-get -y install nginx
echo -e 'Holberton School' > /var/www/html/index.html
sed -i '43i location /redirect_me{\nrewrite ^/(.*)$ https://www.youtube.com/watch?v=EgBJmlPo8Xw permanent;\n}\n' /etc/nginx/sites-available/default
service nginx start
