#!/usr/bin/env bash
# The redirection must be a "301 Moved Permanently"
sudo apt-get update
sudo apt-get -y install nginx
echo -e 'Holberton School' > /var/www/html/index.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.linkedin.com/ permanent;' /etc/nginx/sites-available/default
echo -e 'Ceci n'est pas une page' > /var/www/html/404.html
sed -i 'server_name _;/a error_page 404 /404.html;' /etc/nginx/sites-available/default
service nginx start
