#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
sed -i '/sendfile on;/a add_header X-Served-By $HOSTNAME;' /etc/nginx/nginx.conf 
service nginx start
