#!/usr/bin/env bash
# Install and configure HAproxy
apt-get update
apt-get -y install haproxy=1.9.\*
echo -e "backend web_servers\n\tbalance roundrobin\n\tserver 1222-web-01 104.196.221.76:80 check\n\tserver 1222-web-02 18.234.234.222:80 check" >> /etc/haproxy/haproxy.cfg
