#!/usr/bin/env bash
#
if [ "$#" != 1 ]
then
	echo "Usage: manage_my_process {start|stop|restart}"
elif [ "$@" = "start" ]
then
        ./manage_my_process &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process started"
elif [ "$@" = "stop" ]
then
	pkill -f ./manage_my_process
	rm /var/run/my_process.pid
	echo "manage_my_process stopped"
elif [ "$@" = "restart" ]
then
	pkill -f ./manage_my_process
	rm /var/run/my_process.pid
	./manage_my_process &
	echo $! > /var/run/my_process.pid
        echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
