#!/usr/bin/env bash
# This script is displaying "Holberton School" 9 times and in the iteration 9 display "Hi"
i=1
while [ $i -le 10 ]
do
	if [ "$i" -eq 9 ]
	then
		echo "Hi"
	else
		echo "Holberton school"
	fi
        (( i++ ))
done
