#!/usr/bin/env bash
#script that configures the container to fit the above requirements
pkill apache2
chmod 777 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default 
su nginx -c "service nginx start"
